### ISSUE TITLE
Cannot sync due to a decoding error

### ISSUE THREAD

**Issue by abernatskiy** [TuanTQ15/ens-subgraph-migration#1]
The squid crashes around block 4299559 with an error that indicates an issue with event decoding. Please fix.

A note on a known issue: there are about 50-100 `NewResolver` events early in the contract history that cannot be decoded with typegen-generated code (calls like `abi.events.NewResolver.decode()`). If that is the cause of this issue, please just wrap the `decode()` call in a `try..catch`. The resulting data discrepancy with the subgraph will not affect the acceptance of your submission.

**Comment by HadesDev99** [comment]
@abernatskiy I added `try ...catch`. Please check again, thanks
