### ISSUE TITLE
Errors while syncing

### ISSUE THREAD

**Issue by abernatskiy** [TuanTQ15/ens-subgraph-migration#2]
Made another attempt to sync this submission, got errors:
```
QueryFailedError: null value in column "subdomain_count" of relation "domain" violates not-null constraint
```
and
```
8658491: Cannot mix BigInt and other types, use explicit conversions
```
Please fix.

**Comment by abernatskiy** [comment]
Also, please test the squid before re-submitting. I understand it is challenging given its sync time, but it'll be faster than if I have to find every issue.

You may also find [the new API comparison tool](https://github.com/abernatskiy/compareGraphQL) useful for debugging.

**Comment by HadesDev99** [comment]
Sorry but my laptop can not fully sync, It took more than 35 hrs and the estimated time increasing. I will close my submission.
